export enum InsuranceTypes {
  ALL_PLAN = 'ALL_PLAN',
  MEDICAL_PLAN = 'MEDICAL_PLAN',
  PENSION_PLAN = 'PENSION_PLAN',
  FAMILY_PLAN = 'FAMILY_PLAN',
  CHILDREN_PLAN = 'CHILDREN_PLAN',
  TERM_PLAN = 'TERM_PLAN',
  MOTOR_PLAN = 'MOTOR_PLAN',
  TRAVEL_PLAN = 'TRAVEL_PLAN',
}
