version: '3.6'

services:
  server:
    image: atb00ker/insurance-ng:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./deploy/private.pem:/go/src/app/private.pem:ro
      - ./deploy/jwks.json:/go/src/app/jwks.json:ro
      - ./.env:/go/src/app/.env:ro
      - react_data:/go/src/app/dist/
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - 443:443
    env_file:
      - .env
    volumes:
      - ./deploy/nginx/:/etc/nginx/conf.d/:ro
      - react_data:/etc/nginx/dist/
    entrypoint: [nginx, '-g', 'daemon off;']
    depends_on:
      - db
      - server

  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080

volumes:
  postgres_data: {}
  react_data: {}

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
